app_id: "bed67451-4d86-4411-bc57-5ef78d5ec539"
app_secret: "P34b-QFknSTKshZrPMa.6vwwp9Tru-.7L4"
redirect: "http://localhost:8000/callback"
scopes:
  - user.read
  - mailboxsettings.read
  - calendars.readwrite
  - Schedule.Read.All
  - Schedule.ReadWrite.All
  - Team.ReadBasic.All
  - TeamSettings.Read.All
  - TeamSettings.ReadWrite.All
  - Group.Read.All
  - Group.ReadWrite.All
  - User.Read.All
  - User.ReadWrite.All
  - Directory.Read.All
  - Directory.ReadWrite.All
authority: "https://login.microsoftonline.com/common"